// <auto-generated />
using GoldenCrownSalemApi.Models.EF_Generated_Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GoldenCrownSalemApi.Migrations
{
    [DbContext(typeof(GoldenCrownSalemContext))]
    [Migration("20180809011040_Account.Name to Account.UserName")]
    partial class AccountNametoAccountUserName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Hash")
                        .HasColumnType("binary(36)");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("binary(16)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("AccountId");

                    b.ToTable("Account","Sales");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("CategoryId");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasName("UQ__Category__EDBE0C58103C311F");

                    b.ToTable("Category","Menu");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.CombinationPlateItem", b =>
                {
                    b.Property<int>("CombinationPlateItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DefaultSpicyOptionId");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("CombinationPlateItemId");

                    b.HasIndex("DefaultSpicyOptionId");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasName("UQ__Combinat__EDBE0C587C4DAC49");

                    b.ToTable("CombinationPlateItem","Menu");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.FamilyDinnerItem", b =>
                {
                    b.Property<int>("FamilyDinnerItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DefaultSpicyOptionId");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("FamilyDinnerItemId");

                    b.HasIndex("DefaultSpicyOptionId");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasName("UQ__FamilyDi__EDBE0C58F648D4C2");

                    b.ToTable("FamilyDinnerItem","Menu");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<int?>("DefaultSpicyOptionId");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<bool>("IsAvailable");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("SubLabel")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DefaultSpicyOptionId");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasName("UniqueLabelIndex")
                        .HasFilter("([SubLabel] IS NULL)");

                    b.HasIndex("Label", "SubLabel")
                        .IsUnique()
                        .HasName("UniqueLabelSubLabelIndex")
                        .HasFilter("[Label] IS NOT NULL AND [SubLabel] IS NOT NULL");

                    b.ToTable("MenuItem","Menu");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.MenuItemCombinationPlateItem", b =>
                {
                    b.Property<int>("MenuItemFamilyDinnerItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CombinationPlateItemId");

                    b.Property<int?>("MenuItemId");

                    b.HasKey("MenuItemFamilyDinnerItemId");

                    b.HasIndex("CombinationPlateItemId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuItem_CombinationPlateItem","Menu");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.MenuItemFamilyDinnerItem", b =>
                {
                    b.Property<int>("MenuItemFamilyDinnerItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FamilyDinnerItemId");

                    b.Property<bool>("IsAppetizer");

                    b.Property<bool>("IsEntree");

                    b.Property<bool>("IsSpecial");

                    b.Property<int>("MenuItemId");

                    b.HasKey("MenuItemFamilyDinnerItemId");

                    b.HasIndex("FamilyDinnerItemId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuItem_FamilyDinnerItem","Menu");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<decimal?>("SubTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("money")
                        .HasComputedColumnSql("([Sales].[OrderSubTotal]([OrderId]))");

                    b.Property<decimal>("Tip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("OrderId");

                    b.HasIndex("AccountId");

                    b.ToTable("Order","Sales");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MenuItemId");

                    b.Property<int>("OrderId");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal?>("SubTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("money")
                        .HasComputedColumnSql("([Sales].[OrderItemSubTotal]([MenuItemId],[Quantity]))");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem","Sales");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.SpicyOption", b =>
                {
                    b.Property<int>("SpicyOptionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("SpicyOptionId");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasName("UQ__SpicyOpt__EDBE0C58FAB7CF84");

                    b.ToTable("SpicyOption","Menu");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.CombinationPlateItem", b =>
                {
                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.SpicyOption", "DefaultSpicyOption")
                        .WithMany("CombinationPlateItem")
                        .HasForeignKey("DefaultSpicyOptionId")
                        .HasConstraintName("FK__Combinati__Defau__2D729C23");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.FamilyDinnerItem", b =>
                {
                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.SpicyOption", "DefaultSpicyOption")
                        .WithMany("FamilyDinnerItem")
                        .HasForeignKey("DefaultSpicyOptionId")
                        .HasConstraintName("FK__FamilyDin__Defau__22F50DB0");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.MenuItem", b =>
                {
                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.Category", "Category")
                        .WithMany("MenuItem")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__MenuItem__Catego__1D3C345A");

                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.SpicyOption", "DefaultSpicyOption")
                        .WithMany("MenuItem")
                        .HasForeignKey("DefaultSpicyOptionId")
                        .HasConstraintName("FK__MenuItem__Defaul__1E305893");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.MenuItemCombinationPlateItem", b =>
                {
                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.CombinationPlateItem", "CombinationPlateItem")
                        .WithMany("MenuItemCombinationPlateItem")
                        .HasForeignKey("CombinationPlateItemId")
                        .HasConstraintName("FK__MenuItem___Combi__31432D07");

                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemCombinationPlateItem")
                        .HasForeignKey("MenuItemId")
                        .HasConstraintName("FK__MenuItem___MenuI__304F08CE");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.MenuItemFamilyDinnerItem", b =>
                {
                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.FamilyDinnerItem", "FamilyDinnerItem")
                        .WithMany("MenuItemFamilyDinnerItem")
                        .HasForeignKey("FamilyDinnerItemId")
                        .HasConstraintName("FK__MenuItem___Famil__26C59E94");

                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemFamilyDinnerItem")
                        .HasForeignKey("MenuItemId")
                        .HasConstraintName("FK__MenuItem___MenuI__25D17A5B");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.Order", b =>
                {
                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.Account", "Account")
                        .WithMany("Order")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Order__AccountId__3BC0BB7A");
                });

            modelBuilder.Entity("GoldenCrownSalemApi.Models.EF_Generated_Models.OrderItem", b =>
                {
                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.MenuItem", "MenuItem")
                        .WithMany("OrderItem")
                        .HasForeignKey("MenuItemId")
                        .HasConstraintName("FK__OrderItem__MenuI__40857097");

                    b.HasOne("GoldenCrownSalemApi.Models.EF_Generated_Models.Order", "Order")
                        .WithMany("OrderItem")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderItem__Order__417994D0");
                });
#pragma warning restore 612, 618
        }
    }
}
